apiVersion: gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: ankit-test
  namespace: crossplane-system
spec:
  forProvider:
    autoCreateSubnetworks: false
    description: "Managed by Crossplane"
  providerConfigRef:
    name: default
