apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Subnetwork
metadata:
  name: ankit-test
  namespace: crossplane-system
spec:
  forProvider:
    region: us-central1
    networkRef:
      name: ankit-test
    ipCidrRange: 10.0.0.0/24
  providerConfigRef:
    name: gcp-provider
