apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: my-gke-cluster
  namespace: crossplane-system
spec:
  forProvider:
    location: europe-west9  # or use 'us-central1' for region
    initialNodeCount: 3
    nodeConfig:
      machineType: e2-medium
    networkRef:
      name: ankit-test  # Ensure this Network resource exists
  providerConfigRef:
    name: default
